const properties = [
    {
        "title": "JAHRHUNDERTVILLA MIT AUSBAUPOTENZIAL IN KLOSTERNEUBURG",
        "ID": 101,
        "price": 350000,
        "viewer": 13,
        "type": "Mieten",
        "area": 60,
        "room": 2,
        "bathroom": 2,
        "category": "Haus",
        "address": "5 Example Street, Berlin, Germany",
        "state": "Berlin",
        "city": "Berlin",
        "zipcode": 10115
    },
    {
        "title": "DACHGESCHOSSWOHNUNG MIT BALKON NAHE COTTAGE VIERTEL",
        "ID": 102,
        "price": 400000,
        "viewer": 16,
        "type": "Kaufen",
        "area": 70,
        "room": 3,
        "bathroom": 3,
        "category": "Haus",
        "address": "10 Example Street, Hamburg, Germany",
        "state": "Hamburg",
        "city": "Hamburg",
        "zipcode": 20095
    },
    {
        "title": "MODERNE DG-MAISONETTE MIT BALKON AM AUMANNPLATZ",
        "ID": 103,
        "price": 450000,
        "viewer": 19,
        "type": "Mieten",
        "area": 80,
        "room": 4,
        "bathroom": 4,
        "category": "Wohnung",
        "address": "15 Example Street, Frankfurt, Germany",
        "state": "Hessen",
        "city": "Frankfurt",
        "zipcode": 60311
    },
    {
        "title": "MODERNE DACHGESCHOSSWOHNUNG NÄHE AKH WIEN UND KUTSCHKERMARKTt",
        "ID": 104,
        "price": 500000,
        "viewer": 22,
        "type": "Kaufen",
        "area": 90,
        "room": 5,
        "bathroom": 5,
        "category": "Haus",
        "address": "20 Example Street, Stuttgart, Germany",
        "state": "Baden-W\u00fcrttemberg",
        "city": "Stuttgart",
        "zipcode": 70173
    },
    {
        "title": "GARTEN-MAISONETTE MIT EIGENEM POOL IN DÖBLING",
        "ID": 105,
        "price": 550000,
        "viewer": 25,
        "type": "Mieten",
        "area": 100,
        "room": 6,
        "bathroom": 1,
        "category": "Haus",
        "address": "25 Example Street, Dresden, Germany",
        "state": "Sachsen",
        "city": "Dresden",
        "zipcode": 1067
    },
    {
        "title": "EXQUISITE VILLA MIT WELLNESSBEREICH UND INDOOR-POOL",
        "ID": 106,
        "price": 600000,
        "viewer": 28,
        "type": "Kaufen",
        "area": 110,
        "room": 7,
        "bathroom": 2,
        "category": "Wohnung",
        "address": "30 Example Street, Cologne, Germany",
        "state": "Nordrhein-Westfalen",
        "city": "Cologne",
        "zipcode": 50667
    },
    {
        "title": "SANIERTE 5 ZIMMER DOPPELHAUSHÄLFTE MITSAMT GARTEN UND GEMAUERTEM KAMINOFEN AUF EIGENGRUND",
        "ID": 107,
        "price": 650000,
        "viewer": 31,
        "type": "Mieten",
        "area": 120,
        "room": 1,
        "bathroom": 3,
        "category": "Haus",
        "address": "35 Example Street, Hanover, Germany",
        "state": "Niedersachsen",
        "city": "Hanover",
        "zipcode": 30159
    },
    {
        "title": "HOCHWERTIGE DG-WOHNUNG AUF 2 EBENEN",
        "ID": 108,
        "price": 700000,
        "viewer": 34,
        "type": "Kaufen",
        "area": 130,
        "room": 2,
        "bathroom": 4,
        "category": "Haus",
        "address": "40 Example Street, Mainz, Germany",
        "state": "Rheinland-Pfalz",
        "city": "Mainz",
        "zipcode": 55116
    },
    {
        "title": "GARTEN-MAISONETTE MIT EIGENEM POOL IN DÖBLING",
        "ID": 109,
        "price": 750000,
        "viewer": 37,
        "type": "Mieten",
        "area": 140,
        "room": 3,
        "bathroom": 5,
        "category": "Wohnung",
        "address": "45 Example Street, Saarbr\u00fccken, Germany",
        "state": "Saarland",
        "city": "Saarbr\u00fccken",
        "zipcode": 66111
    },
    {
        "title": "Property 10 in Munich",
        "ID": 110,
        "price": 800000,
        "viewer": 40,
        "type": "Kaufen",
        "area": 150,
        "room": 4,
        "bathroom": 1,
        "category": "Haus",
        "address": "50 Example Street, Munich, Germany",
        "state": "Bayern",
        "city": "Munich",
        "zipcode": 80331
    },
    {
        "title": "Property 11 in Berlin",
        "ID": 111,
        "price": 850000,
        "viewer": 43,
        "type": "Mieten",
        "area": 160,
        "room": 5,
        "bathroom": 2,
        "category": "Haus",
        "address": "55 Example Street, Berlin, Germany",
        "state": "Berlin",
        "city": "Berlin",
        "zipcode": 10115
    },
    {
        "title": "Property 12 in Hamburg",
        "ID": 112,
        "price": 900000,
        "viewer": 46,
        "type": "Kaufen",
        "area": 170,
        "room": 6,
        "bathroom": 3,
        "category": "Wohnung",
        "address": "60 Example Street, Hamburg, Germany",
        "state": "Hamburg",
        "city": "Hamburg",
        "zipcode": 20095
    },
    {
        "title": "Property 13 in Frankfurt",
        "ID": 113,
        "price": 950000,
        "viewer": 49,
        "type": "Mieten",
        "area": 180,
        "room": 7,
        "bathroom": 4,
        "category": "Haus",
        "address": "65 Example Street, Frankfurt, Germany",
        "state": "Hessen",
        "city": "Frankfurt",
        "zipcode": 60311
    },
    {
        "title": "Property 14 in Stuttgart",
        "ID": 114,
        "price": 1000000,
        "viewer": 52,
        "type": "Kaufen",
        "area": 190,
        "room": 1,
        "bathroom": 5,
        "category": "Haus",
        "address": "70 Example Street, Stuttgart, Germany",
        "state": "Baden-W\u00fcrttemberg",
        "city": "Stuttgart",
        "zipcode": 70173
    },
    {
        "title": "Property 15 in Dresden",
        "ID": 115,
        "price": 1050000,
        "viewer": 55,
        "type": "Mieten",
        "area": 200,
        "room": 2,
        "bathroom": 1,
        "category": "Wohnung",
        "address": "75 Example Street, Dresden, Germany",
        "state": "Sachsen",
        "city": "Dresden",
        "zipcode": 1067
    },
    {
        "title": "Property 16 in Cologne",
        "ID": 116,
        "price": 1100000,
        "viewer": 58,
        "type": "Kaufen",
        "area": 210,
        "room": 3,
        "bathroom": 2,
        "category": "Haus",
        "address": "80 Example Street, Cologne, Germany",
        "state": "Nordrhein-Westfalen",
        "city": "Cologne",
        "zipcode": 50667
    },
    {
        "title": "Property 17 in Hanover",
        "ID": 117,
        "price": 1150000,
        "viewer": 11,
        "type": "Mieten",
        "area": 220,
        "room": 4,
        "bathroom": 3,
        "category": "Haus",
        "address": "85 Example Street, Hanover, Germany",
        "state": "Niedersachsen",
        "city": "Hanover",
        "zipcode": 30159
    },
    {
        "title": "Property 18 in Mainz",
        "ID": 118,
        "price": 1200000,
        "viewer": 14,
        "type": "Kaufen",
        "area": 230,
        "room": 5,
        "bathroom": 4,
        "category": "Wohnung",
        "address": "90 Example Street, Mainz, Germany",
        "state": "Rheinland-Pfalz",
        "city": "Mainz",
        "zipcode": 55116
    },
    {
        "title": "Property 19 in Saarbr\u00fccken",
        "ID": 119,
        "price": 1250000,
        "viewer": 17,
        "type": "Mieten",
        "area": 240,
        "room": 6,
        "bathroom": 5,
        "category": "Haus",
        "address": "95 Example Street, Saarbr\u00fccken, Germany",
        "state": "Saarland",
        "city": "Saarbr\u00fccken",
        "zipcode": 66111
    },
    {
        "title": "Property 20 in Munich",
        "ID": 120,
        "price": 1300000,
        "viewer": 20,
        "type": "Kaufen",
        "area": 250,
        "room": 7,
        "bathroom": 1,
        "category": "Haus",
        "address": "100 Example Street, Munich, Germany",
        "state": "Bayern",
        "city": "Munich",
        "zipcode": 80331
    },
    {
        "title": "Property 21 in Berlin",
        "ID": 121,
        "price": 1350000,
        "viewer": 23,
        "type": "Mieten",
        "area": 260,
        "room": 1,
        "bathroom": 2,
        "category": "Wohnung",
        "address": "105 Example Street, Berlin, Germany",
        "state": "Berlin",
        "city": "Berlin",
        "zipcode": 10115
    },
    {
        "title": "Property 22 in Hamburg",
        "ID": 122,
        "price": 1400000,
        "viewer": 26,
        "type": "Kaufen",
        "area": 270,
        "room": 2,
        "bathroom": 3,
        "category": "Haus",
        "address": "110 Example Street, Hamburg, Germany",
        "state": "Hamburg",
        "city": "Hamburg",
        "zipcode": 20095
    },
    {
        "title": "Property 23 in Frankfurt",
        "ID": 123,
        "price": 1450000,
        "viewer": 29,
        "type": "Mieten",
        "area": 280,
        "room": 3,
        "bathroom": 4,
        "category": "Haus",
        "address": "115 Example Street, Frankfurt, Germany",
        "state": "Hessen",
        "city": "Frankfurt",
        "zipcode": 60311
    },
    {
        "title": "Property 24 in Stuttgart",
        "ID": 124,
        "price": 1500000,
        "viewer": 32,
        "type": "Kaufen",
        "area": 290,
        "room": 4,
        "bathroom": 5,
        "category": "Wohnung",
        "address": "120 Example Street, Stuttgart, Germany",
        "state": "Baden-W\u00fcrttemberg",
        "city": "Stuttgart",
        "zipcode": 70173
    },
    {
        "title": "Property 25 in Dresden",
        "ID": 125,
        "price": 1550000,
        "viewer": 35,
        "type": "Mieten",
        "area": 300,
        "room": 5,
        "bathroom": 1,
        "category": "Haus",
        "address": "125 Example Street, Dresden, Germany",
        "state": "Sachsen",
        "city": "Dresden",
        "zipcode": 1067
    },
    {
        "title": "Property 26 in Cologne",
        "ID": 126,
        "price": 1600000,
        "viewer": 38,
        "type": "Kaufen",
        "area": 310,
        "room": 6,
        "bathroom": 2,
        "category": "Haus",
        "address": "130 Example Street, Cologne, Germany",
        "state": "Nordrhein-Westfalen",
        "city": "Cologne",
        "zipcode": 50667
    },
    {
        "title": "Property 27 in Hanover",
        "ID": 127,
        "price": 1650000,
        "viewer": 41,
        "type": "Mieten",
        "area": 320,
        "room": 7,
        "bathroom": 3,
        "category": "Wohnung",
        "address": "135 Example Street, Hanover, Germany",
        "state": "Niedersachsen",
        "city": "Hanover",
        "zipcode": 30159
    },
    {
        "title": "Property 28 in Mainz",
        "ID": 128,
        "price": 1700000,
        "viewer": 44,
        "type": "Kaufen",
        "area": 330,
        "room": 1,
        "bathroom": 4,
        "category": "Haus",
        "address": "140 Example Street, Mainz, Germany",
        "state": "Rheinland-Pfalz",
        "city": "Mainz",
        "zipcode": 55116
    },
    {
        "title": "Property 29 in Saarbr\u00fccken",
        "ID": 129,
        "price": 1750000,
        "viewer": 47,
        "type": "Mieten",
        "area": 340,
        "room": 2,
        "bathroom": 5,
        "category": "Haus",
        "address": "145 Example Street, Saarbr\u00fccken, Germany",
        "state": "Saarland",
        "city": "Saarbr\u00fccken",
        "zipcode": 66111
    },
    {
        "title": "Property 30 in Munich",
        "ID": 130,
        "price": 1800000,
        "viewer": 50,
        "type": "Kaufen",
        "area": 350,
        "room": 3,
        "bathroom": 1,
        "category": "Wohnung",
        "address": "150 Example Street, Munich, Germany",
        "state": "Bayern",
        "city": "Munich",
        "zipcode": 80331
    },
    {
        "title": "Property 31 in Berlin",
        "ID": 131,
        "price": 1850000,
        "viewer": 53,
        "type": "Mieten",
        "area": 360,
        "room": 4,
        "bathroom": 2,
        "category": "Haus",
        "address": "155 Example Street, Berlin, Germany",
        "state": "Berlin",
        "city": "Berlin",
        "zipcode": 10115
    },
    {
        "title": "Property 32 in Hamburg",
        "ID": 132,
        "price": 1900000,
        "viewer": 56,
        "type": "Kaufen",
        "area": 370,
        "room": 5,
        "bathroom": 3,
        "category": "Haus",
        "address": "160 Example Street, Hamburg, Germany",
        "state": "Hamburg",
        "city": "Hamburg",
        "zipcode": 20095
    },
    {
        "title": "Property 33 in Frankfurt",
        "ID": 133,
        "price": 1950000,
        "viewer": 59,
        "type": "Mieten",
        "area": 380,
        "room": 6,
        "bathroom": 4,
        "category": "Wohnung",
        "address": "165 Example Street, Frankfurt, Germany",
        "state": "Hessen",
        "city": "Frankfurt",
        "zipcode": 60311
    },
    {
        "title": "Property 34 in Stuttgart",
        "ID": 134,
        "price": 2000000,
        "viewer": 12,
        "type": "Kaufen",
        "area": 390,
        "room": 7,
        "bathroom": 5,
        "category": "Haus",
        "address": "170 Example Street, Stuttgart, Germany",
        "state": "Baden-W\u00fcrttemberg",
        "city": "Stuttgart",
        "zipcode": 70173
    },
    {
        "title": "Property 35 in Dresden",
        "ID": 135,
        "price": 2050000,
        "viewer": 15,
        "type": "Mieten",
        "area": 400,
        "room": 1,
        "bathroom": 1,
        "category": "Haus",
        "address": "175 Example Street, Dresden, Germany",
        "state": "Sachsen",
        "city": "Dresden",
        "zipcode": 1067
    },
    {
        "title": "Property 36 in Cologne",
        "ID": 136,
        "price": 2100000,
        "viewer": 18,
        "type": "Kaufen",
        "area": 410,
        "room": 2,
        "bathroom": 2,
        "category": "Wohnung",
        "address": "180 Example Street, Cologne, Germany",
        "state": "Nordrhein-Westfalen",
        "city": "Cologne",
        "zipcode": 50667
    },
    {
        "title": "Property 37 in Hanover",
        "ID": 137,
        "price": 2150000,
        "viewer": 21,
        "type": "Mieten",
        "area": 420,
        "room": 3,
        "bathroom": 3,
        "category": "Haus",
        "address": "185 Example Street, Hanover, Germany",
        "state": "Niedersachsen",
        "city": "Hanover",
        "zipcode": 30159
    },
    {
        "title": "Property 38 in Mainz",
        "ID": 138,
        "price": 2200000,
        "viewer": 24,
        "type": "Kaufen",
        "area": 430,
        "room": 4,
        "bathroom": 4,
        "category": "Haus",
        "address": "190 Example Street, Mainz, Germany",
        "state": "Rheinland-Pfalz",
        "city": "Mainz",
        "zipcode": 55116
    },
    {
        "title": "Property 39 in Saarbr\u00fccken",
        "ID": 139,
        "price": 2250000,
        "viewer": 27,
        "type": "Mieten",
        "area": 440,
        "room": 5,
        "bathroom": 5,
        "category": "Wohnung",
        "address": "195 Example Street, Saarbr\u00fccken, Germany",
        "state": "Saarland",
        "city": "Saarbr\u00fccken",
        "zipcode": 66111
    },
    {
        "title": "Property 40 in Munich",
        "ID": 140,
        "price": 300000,
        "viewer": 30,
        "type": "Kaufen",
        "area": 50,
        "room": 6,
        "bathroom": 1,
        "category": "Haus",
        "address": "200 Example Street, Munich, Germany",
        "state": "Bayern",
        "city": "Munich",
        "zipcode": 80331
    }
];

module.exports = properties;
